import { describe, expect, test } from '@jest/globals';

import { TauriAtomicArtworkWriter } from '../atomicArtworkWriter';

describe('TauriAtomicArtworkWriter', () => {
  test('uses write_file_atomic for generated bytes and copy_file_atomic for existing paths', async () => {
    const calls: Array<{ command: string; args: Record<string, unknown> }> = [];
    const invokeCommand = async <T>(command: string, args: Record<string, unknown>): Promise<T> => {
      calls.push({ command, args });
      return undefined as T;
    };
    const writer = new TauriAtomicArtworkWriter(invokeCommand);

    await writer.writeGenerated(
      'E:\\tmp\\generated.webp',
      new Blob([Uint8Array.from([1, 2, 3]).buffer], { type: 'image/webp' })
    );
    await writer.copyExisting('E:\\source.webp', 'E:\\tmp\\copied.webp');

    expect(calls).toEqual([
      {
        command: 'write_file_atomic',
        args: { path: 'E:\\tmp\\generated.webp', contents: [1, 2, 3] }
      },
      {
        command: 'copy_file_atomic',
        args: { source: 'E:\\source.webp', destination: 'E:\\tmp\\copied.webp' }
      }
    ]);
  });
});
